# Exercise 4.8.2


# Index

01 Importing Libraries

02 Importing Data

03 Analysing Data

04 Exercise Questions

# 01. Importing Libraries


In [1]:
# importing libraries
import pandas as pd
import numpy as np
import os

# 02. Importing Data

In [4]:
# create path
path = r'C:\Users\kthav\My Pc\Desktop\Career Foundry\Data Immersion\Python Fundamentals for Data Analytics\11-12-2024 Instacart Basket Analysis'

In [6]:
path


'C:\\Users\\kthav\\My Pc\\Desktop\\Career Foundry\\Data Immersion\\Python Fundamentals for Data Analytics\\11-12-2024 Instacart Basket Analysis'

In [8]:
# import ords_prods_merge_derived as ords_prods_merge
ords_prods_merge = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_merged_derived.pkl'))

In [10]:
ords_prods_merge.shape

(32251812, 18)

In [13]:
ords_prods_merge.head(20)

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0    2539329        1             1                   2                  8   
1    2539329        1             1                   2                  8   
2    2539329        1             1                   2                  8   
3    2539329        1             1                   2                  8   
4    2539329        1             1                   2                  8   
5    2398795        1             2                   3                  7   
6    2398795        1             2                   3                  7   
7    2398795        1             2                   3                  7   
8    2398795        1             2                   3                  7   
9    2398795        1             2                   3                  7   
10   2398795        1             2                   3                  7   
11    473747        1             3                   3                 12   
12    473747        1             3                   3                 12   
13    473747        1             3                   3                 12   
14    473747        1             3                   3                 12   
15    473747        1             3                   3                 12   
16   2254736        1             4                   4                  7   
17   2254736        1             4                   4                  7   
18   2254736        1             4                   4                  7   
19   2254736        1             4                   4                  7   

    days_since_last_order  first_order  product_id  add_to_cart_order  \
0                     NaN         True         196                  1   
1                     NaN         True       14084                  2   
2                     NaN         True       12427                  3   
3                     NaN         True       26088                  4   
4                     NaN         True       26405                  5   
5                    15.0        False         196                  1   
6                    15.0        False       10258                  2   
7                    15.0        False       12427                  3   
8                    15.0        False       13176                  4   
9                    15.0        False       26088                  5   
10                   15.0        False       13032                  6   
11                   21.0        False         196                  1   
12                   21.0        False       12427                  2   
13                   21.0        False       10258                  3   
14                   21.0        False       25133                  4   
15                   21.0        False       30450                  5   
16                   29.0        False         196                  1   
17                   29.0        False       12427                  2   
18                   29.0        False       10258                  3   
19                   29.0        False       25133                  4   

    reordered                             product_name  aisle_id  \
0           0                                     Soda        77   
1           0  Organic Unsweetened Vanilla Almond Milk        91   
2           0                      Original Beef Jerky        23   
3           0               Aged White Cheddar Popcorn        23   
4           0         XL Pick-A-Size Paper Towel Rolls        54   
5           1                                     Soda        77   
6           0                               Pistachios       117   
7           1                      Original Beef Jerky        23   
8           0                   Bag of Organic Bananas        24   
9           1               Aged White Cheddar Popcorn        23   
10          0                    Cinnamon Toast Crunch       121   
11          1  

# 03 Analysing Data

In [16]:
# calculate aggregated mean for 'order_number' grouped by 'department_id' across the entire dataframe
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

order_number
                      mean
department_id             
1                15.460534
2                17.286638
3                17.172038
4                17.810881
5                15.240163
6                16.448202
7                17.223840
8                15.350714
9                15.901078
10               20.205048
11               16.176624
12               15.887239
13               16.585371
14               16.777331
15               16.173986
16               17.666859
17               15.702001
18               19.316541
19               17.182316
20               16.473120
21               22.913538

# 04. Exercise Questions

# Question 3
Both aggregations seem quite similiar to each other. The aggreagtion for the entire dataset has both higher and lower values compared to the subset however, the differences are small. Most accurate results will be obtained from the entire dataset.

# Question 4

I will first create a new column called 'max_value' that will indiacte the customers total orders. Then create another column called loyalty flag to indicate whether the customer is Loyal - 40 orders and above, Regular - in between 10 and 40 orders and new customer less than 10 orders:

In [21]:
# create 'max_order' column by grouping 'user_id' to determine amount of orders that each customer places
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\kthav\AppData\Local\Temp\ipykernel_17812\4153739739.py:2: FutureWarning: The provided callable <function max at 0x000001D68BB74400> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)


In [23]:
ords_prods_merge.head(10)

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0   2539329        1             1                   2                  8   
1   2539329        1             1                   2                  8   
2   2539329        1             1                   2                  8   
3   2539329        1             1                   2                  8   
4   2539329        1             1                   2                  8   
5   2398795        1             2                   3                  7   
6   2398795        1             2                   3                  7   
7   2398795        1             2                   3                  7   
8   2398795        1             2                   3                  7   
9   2398795        1             2                   3                  7   

   days_since_last_order  first_order  product_id  add_to_cart_order  \
0                    NaN         True         196                  1   
1                    NaN         True       14084                  2   
2                    NaN         True       12427                  3   
3                    NaN         True       26088                  4   
4                    NaN         True       26405                  5   
5                   15.0        False         196                  1   
6                   15.0        False       10258                  2   
7                   15.0        False       12427                  3   
8                   15.0        False       13176                  4   
9                   15.0        False       26088                  5   

   reordered                             product_name  aisle_id  \
0          0                                     Soda        77   
1          0  Organic Unsweetened Vanilla Almond Milk        91   
2          0                      Original Beef Jerky        23   
3          0               Aged White Cheddar Popcorn        23   
4          0         XL Pick-A-Size Paper Towel Rolls        54   
5          1                                     Soda        77   
6          0                               Pistachios       117   
7          1                      Original Beef Jerky        23   
8          0                   Bag of Organic Bananas        24   
9          1               Aged White Cheddar Popcorn        23   

   department_id  prices _merge     busiest_day   busiest days  \
0              7     9.0   both  Regularly busy  Regulary busy   
1             16    12.5   both  Regularly busy  Regulary busy   
2             19     4.4   both  Regularly busy  Regulary busy   
3             19     4.7   both  Regularly busy  Regulary busy   
4             17     1.0   both  Regularly busy  Regulary busy   
5              7     9.0   both  Regularly busy   Slowest days   
6             19     3.0   both  Regularly busy   Slowest days   
7             19     4.4   both  Regularly busy   Slowest days   
8              4    10.3   both  Regularly busy   Slowest days   
9             19     4.7   both  Regularly busy   Slowest days   

  busiest_period_of_day  max_order  
0        Average orders         10  
1        Average orders         10  
2        Average orders         10  
3        Average orders         10  
4        Average orders         10  
5        Average orders         10  
6        Average orders         10  
7        Average orders         10  
8        Average orders         10  
9        Average orders         10

In [25]:
# create column 'loyalty_flag' to flag loyal customers
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [27]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [29]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [31]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15800757
Loyal customer      10237475
New customer         6213580
Name: count, dtype: int64

In [33]:
# check column for errors
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1

# Question 5

I will first group  the data on the 'loyalty flag' column and then calculate the agg basic stats on the 'price'( mean, min, max, median, std) for each column.

In [37]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'std', 'median']})

prices                                 
                       mean  min      max         std median
loyalty_flag                                                
Loyal customer    10.398445  1.0  99999.0  328.763608    7.4
New customer      13.302514  1.0  99999.0  598.782370    7.4
Regular customer  12.492589  1.0  99999.0  539.664845    7.4

The max values of 99999.0 look unrealestic. In order to get more accurate results I will filtered out these values and redo the basic stats.

In [39]:
# Create a new DataFrame excluding rows where 'prices' equals 99999
ords_prods_filtered = ords_prods_merge[ords_prods_merge['prices'] != 99999]

# Display the filtered DataFrame
print(ords_prods_filtered)


          order_id  user_id  order_number  orders_day_of_week  \
0          2539329        1             1                   2   
1          2539329        1             1                   2   
2          2539329        1             1                   2   
3          2539329        1             1                   2   
4          2539329        1             1                   2   
...            ...      ...           ...                 ...   
32251807    451891   205205            13                   4   
32251808    451891   205205            13                   4   
32251809    451891   205205            13                   4   
32251810    451891   205205            13                   4   
32251811    451891   205205            13                   4   

          order_hour_of_day  days_since_last_order  first_order  product_id  \
0                         8                    NaN         True         196   
1                         8                    NaN         Tr

In [40]:
ords_prods_filtered.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'std', 'median']})

prices                                 
                       mean  min      max         std median
loyalty_flag                                                
Loyal customer     9.587784  1.0  14900.0  164.404582    7.4
New customer      10.051929  1.0  14900.0  183.110336    7.4
Regular customer   9.891731  1.0  14900.0  176.601934    7.4

The max values of 14900.0 look unrealestic. In order to get more accurate results I will filtered out these values and redo the basic stats.

In [43]:
# Create a new DataFrame excluding rows where 'prices' equals 14900
ords_prods_filtered_2 = ords_prods_filtered[ords_prods_filtered['prices'] != 14900]



In [44]:
ords_prods_filtered_2.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'std', 'median']})

prices                            
                      mean  min   max       std median
loyalty_flag                                          
Loyal customer    7.773786  1.0  25.0  4.206148    7.4
New customer      7.801338  1.0  25.0  4.266702    7.4
Regular customer  7.798386  1.0  25.0  4.255084    7.4

The stats look fairly similiar for each customer groups with min, max and median values the same.

# Question 6

I will first create a new column called 'average_spend'. I will group the data by 'user_id' and calculate the average spend by finding the average of the 'prices' column for each 'user_id'. Then I will create a new column Spender_flag to highlight the status of the customer.

High Spenders = average spend > 10
Low Spenders = avergae spend < 10

In [48]:
# Create a new column for the average spending of a customer
ords_prods_filtered_2['average_spend'] = ords_prods_filtered_2.groupby(['user_id'])['prices'].transform('mean')

C:\Users\kthav\AppData\Local\Temp\ipykernel_17812\3151406747.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ords_prods_filtered_2['average_spend'] = ords_prods_filtered_2.groupby(['user_id'])['prices'].transform('mean')


To be able to complete this action I need to create a copy of the ords_prods_filtered_2. However my memory does not allow this, so I will be exporting the data and re-importing it to bypass this problem.

# 05. Exporting Data

In [55]:
# export ords_prods_filtered_2 as orders_products_merged_filtered.pkl
ords_prods_filtered_2.to_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_merged_filtered.pkl'))

# 0. Re-Importing Data

In [63]:
# impprt orders_products_merged_filtered.pkl as df_opm
df_opm = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_merged_filtered.pkl'))

In [66]:
df_opm.head(10)

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0   2539329        1             1                   2                  8   
1   2539329        1             1                   2                  8   
2   2539329        1             1                   2                  8   
3   2539329        1             1                   2                  8   
4   2539329        1             1                   2                  8   
5   2398795        1             2                   3                  7   
6   2398795        1             2                   3                  7   
7   2398795        1             2                   3                  7   
8   2398795        1             2                   3                  7   
9   2398795        1             2                   3                  7   

   days_since_last_order  first_order  product_id  add_to_cart_order  \
0                    NaN         True         196                  1   
1                    NaN         True       14084                  2   
2                    NaN         True       12427                  3   
3                    NaN         True       26088                  4   
4                    NaN         True       26405                  5   
5                   15.0        False         196                  1   
6                   15.0        False       10258                  2   
7                   15.0        False       12427                  3   
8                   15.0        False       13176                  4   
9                   15.0        False       26088                  5   

   reordered  ... aisle_id  department_id  prices  _merge     busiest_day  \
0          0  ...       77              7     9.0    both  Regularly busy   
1          0  ...       91             16    12.5    both  Regularly busy   
2          0  ...       23             19     4.4    both  Regularly busy   
3          0  ...       23             19     4.7    both  Regularly busy   
4          0  ...       54             17     1.0    both  Regularly busy   
5          1  ...       77              7     9.0    both  Regularly busy   
6          0  ...      117             19     3.0    both  Regularly busy   
7          1  ...       23             19     4.4    both  Regularly busy   
8          0  ...       24              4    10.3    both  Regularly busy   
9          1  ...       23             19     4.7    both  Regularly busy   

    busiest days busiest_period_of_day max_order  loyalty_flag average_spend  
0  Regulary busy        Average orders        10  New customer      6.367797  
1  Regulary busy        Average orders        10  New customer      6.367797  
2  Regulary busy        Average orders        10  New customer      6.367797  
3  Regulary busy        Average orders        10  New customer      6.367797  
4  Regulary busy        Average orders        10  New customer      6.367797  
5   Slowest days        Average orders        10  New customer      6.367797  
6   Slowest days        Average orders        10  New customer      6.367797  
7   Slowest days        Average orders        10  New customer      6.367797  
8   Slowest days        Average orders        10  New customer      6.367797  
9   Slowest days        Average orders        10  New customer      6.367797  

[10 rows x 21 columns]

# Question 6

In [68]:
# Create a new column for the average spending of a customer
df_opm['average_spend'] = df_opm.groupby(['user_id'])['prices'].transform('mean')

In [70]:
df_opm.head(10)

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0   2539329        1             1                   2                  8   
1   2539329        1             1                   2                  8   
2   2539329        1             1                   2                  8   
3   2539329        1             1                   2                  8   
4   2539329        1             1                   2                  8   
5   2398795        1             2                   3                  7   
6   2398795        1             2                   3                  7   
7   2398795        1             2                   3                  7   
8   2398795        1             2                   3                  7   
9   2398795        1             2                   3                  7   

   days_since_last_order  first_order  product_id  add_to_cart_order  \
0                    NaN         True         196                  1   
1                    NaN         True       14084                  2   
2                    NaN         True       12427                  3   
3                    NaN         True       26088                  4   
4                    NaN         True       26405                  5   
5                   15.0        False         196                  1   
6                   15.0        False       10258                  2   
7                   15.0        False       12427                  3   
8                   15.0        False       13176                  4   
9                   15.0        False       26088                  5   

   reordered  ... aisle_id  department_id  prices  _merge     busiest_day  \
0          0  ...       77              7     9.0    both  Regularly busy   
1          0  ...       91             16    12.5    both  Regularly busy   
2          0  ...       23             19     4.4    both  Regularly busy   
3          0  ...       23             19     4.7    both  Regularly busy   
4          0  ...       54             17     1.0    both  Regularly busy   
5          1  ...       77              7     9.0    both  Regularly busy   
6          0  ...      117             19     3.0    both  Regularly busy   
7          1  ...       23             19     4.4    both  Regularly busy   
8          0  ...       24              4    10.3    both  Regularly busy   
9          1  ...       23             19     4.7    both  Regularly busy   

    busiest days busiest_period_of_day max_order  loyalty_flag average_spend  
0  Regulary busy        Average orders        10  New customer      6.367797  
1  Regulary busy        Average orders        10  New customer      6.367797  
2  Regulary busy        Average orders        10  New customer      6.367797  
3  Regulary busy        Average orders        10  New customer      6.367797  
4  Regulary busy        Average orders        10  New customer      6.367797  
5   Slowest days        Average orders        10  New customer      6.367797  
6   Slowest days        Average orders        10  New customer      6.367797  
7   Slowest days        Average orders        10  New customer      6.367797  
8   Slowest days        Average orders        10  New customer      6.367797  
9   Slowest days        Average orders        10  New customer      6.367797  

[10 rows x 21 columns]

In [76]:
# Assign spender tag to each customer
df_opm.loc[df_opm['average_spend']<10,'spender_flag']='Low_spender'

In [96]:
df_opm.loc[df_opm['average_spend']>= 10, 'spender_flag'] = 'High_spender'

In [100]:
df_opm.head()

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0   2539329        1             1                   2                  8   
1   2539329        1             1                   2                  8   
2   2539329        1             1                   2                  8   
3   2539329        1             1                   2                  8   
4   2539329        1             1                   2                  8   

   days_since_last_order  first_order  product_id  add_to_cart_order  \
0                    NaN         True         196                  1   
1                    NaN         True       14084                  2   
2                    NaN         True       12427                  3   
3                    NaN         True       26088                  4   
4                    NaN         True       26405                  5   

   reordered  ... prices  _merge     busiest_day   busiest days  \
0          0  ...    9.0    both  Regularly busy  Regulary busy   
1          0  ...   12.5    both  Regularly busy  Regulary busy   
2          0  ...    4.4    both  Regularly busy  Regulary busy   
3          0  ...    4.7    both  Regularly busy  Regulary busy   
4          0  ...    1.0    both  Regularly busy  Regulary busy   

  busiest_period_of_day max_order  loyalty_flag average_spend  spender_flag  \
0        Average orders        10  New customer      6.367797   Low_spender   
1        Average orders        10  New customer      6.367797   Low_spender   
2        Average orders        10  New customer      6.367797   Low_spender   
3        Average orders        10  New customer      6.367797   Low_spender   
4        Average orders        10  New customer      6.367797   Low_spender   

  customer_frequency  
0               20.5  
1               20.5  
2               20.5  
3               20.5  
4               20.5  

[5 rows x 23 columns]

In [80]:
# Check spender flags
df_opm['spender_flag'].value_counts(dropna = False)

spender_flag
Low_spender     32127789
High_spender      118920
Name: count, dtype: int64

High Spenders represent around 0,37% of total customers which is considerably lower than low spenders. 

# Question 7

I will first create a new column called 'customer frequency'. I will group the data by 'user_id' and calculate the median days of öast order by finding the median of the 'days_since_prior_order' column for each 'user_id'.  Then I will create a new column customer_frequency to highlight the status of the customer.


Non-frequent customer = more than 20 days since last order

Regular customer = higher than 10 but less than or equal to 20  days since last order

Frequent customer = less than or equal to 10 days from last order

In [92]:
# Create a new column for customer frequency flags based on the median values from 'days_since_prior_order' column
df_opm['customer_frequency'] = df_opm.groupby(['user_id'])['days_since_last_order'].transform('median')

In [94]:
# Check that the column was created successfully and properly
df_opm.head(20)

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0    2539329        1             1                   2                  8   
1    2539329        1             1                   2                  8   
2    2539329        1             1                   2                  8   
3    2539329        1             1                   2                  8   
4    2539329        1             1                   2                  8   
5    2398795        1             2                   3                  7   
6    2398795        1             2                   3                  7   
7    2398795        1             2                   3                  7   
8    2398795        1             2                   3                  7   
9    2398795        1             2                   3                  7   
10   2398795        1             2                   3                  7   
11    473747        1             3                   3                 12   
12    473747        1             3                   3                 12   
13    473747        1             3                   3                 12   
14    473747        1             3                   3                 12   
15    473747        1             3                   3                 12   
16   2254736        1             4                   4                  7   
17   2254736        1             4                   4                  7   
18   2254736        1             4                   4                  7   
19   2254736        1             4                   4                  7   

    days_since_last_order  first_order  product_id  add_to_cart_order  \
0                     NaN         True         196                  1   
1                     NaN         True       14084                  2   
2                     NaN         True       12427                  3   
3                     NaN         True       26088                  4   
4                     NaN         True       26405                  5   
5                    15.0        False         196                  1   
6                    15.0        False       10258                  2   
7                    15.0        False       12427                  3   
8                    15.0        False       13176                  4   
9                    15.0        False       26088                  5   
10                   15.0        False       13032                  6   
11                   21.0        False         196                  1   
12                   21.0        False       12427                  2   
13                   21.0        False       10258                  3   
14                   21.0        False       25133                  4   
15                   21.0        False       30450                  5   
16                   29.0        False         196                  1   
17                   29.0        False       12427                  2   
18                   29.0        False       10258                  3   
19                   29.0        False       25133                  4   

    reordered  ... prices  _merge     busiest_day   busiest days  \
0           0  ...    9.0    both  Regularly busy  Regulary busy   
1           0  ...   12.5    both  Regularly busy  Regulary busy   
2           0  ...    4.4    both  Regularly busy  Regulary busy   
3           0  ...    4.7    both  Regularly busy  Regulary busy   
4           0  ...    1.0    both  Regularly busy  Regulary busy   
5           1  ...    9.0    both  Regularly busy   Slowest days   
6           0  ...    3.0    both  Regularly busy   Slowest days   
7           1  ...    4.4    both  Regularly busy   Slowest days   
8           0  ...   10.3    both  Regularly busy   Slowest days   
9           1  ...    4.7    both  Regularly busy   Slowest days   
10          0  ...    4.0    both  Regularly busy   Slowest days   
11          1  

In [104]:
# Based on the criteria provided, create a column featuring order frequency flags
df_opm.loc[df_opm['customer_frequency'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [106]:
df_opm.loc[(df_opm['customer_frequency'] > 10) & (df_opm['customer_frequency'] <=20), 'frequency_flag'] = 'Regular customer'

In [108]:
df_opm.loc[df_opm['customer_frequency'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [110]:
# Check value counts for new column
df_opm['frequency_flag'].value_counts(dropna = False)


frequency_flag
Frequent customer        21454217
Regular customer          7176057
Non-frequent customer     3616430
NaN                             5
Name: count, dtype: int64

In [114]:
df_opm[['user_id', 'customer_frequency', 'frequency_flag']].head(60)

user_id  customer_frequency         frequency_flag
0         1                20.5  Non-frequent customer
1         1                20.5  Non-frequent customer
2         1                20.5  Non-frequent customer
3         1                20.5  Non-frequent customer
4         1                20.5  Non-frequent customer
5         1                20.5  Non-frequent customer
6         1                20.5  Non-frequent customer
7         1                20.5  Non-frequent customer
8         1                20.5  Non-frequent customer
9         1                20.5  Non-frequent customer
10        1                20.5  Non-frequent customer
11        1                20.5  Non-frequent customer
12        1                20.5  Non-frequent customer
13        1                20.5  Non-frequent customer
14        1                20.5  Non-frequent customer
15        1                20.5  Non-frequent customer
16        1                20.5  Non-frequent customer
17        1                20.5  Non-frequent customer
18        1                20.5  Non-frequent customer
19        1                20.5  Non-frequent customer
20        1                20.5  Non-frequent customer
21        1                20.5  Non-frequent customer
22        1                20.5  Non-frequent customer
23        1                20.5  Non-frequent customer
24        1                20.5  Non-frequent customer
25        1                20.5  Non-frequent customer
26        1                20.5  Non-frequent customer
27        1                20.5  Non-frequent customer
28        1                20.5  Non-frequent customer
29        1                20.5  Non-frequent customer
30        1                20.5  Non-frequent customer
31        1                20.5  Non-frequent customer
32        1                20.5  Non-frequent customer
33        1                20.5  Non-frequent customer
34        1                20.5  Non-frequent customer
35        1                20.5  Non-frequent customer
36        1                20.5  Non-frequent customer
37        1                20.5  Non-frequent customer
38        1                20.5  Non-frequent customer
39        1                20.5  Non-frequent customer
40        1                20.5  Non-frequent customer
41        1                20.5  Non-frequent customer
42        1                20.5  Non-frequent customer
43        1                20.5  Non-frequent customer
44        1                20.5  Non-frequent customer
45        1                20.5  Non-frequent customer
46        1                20.5  Non-frequent customer
47        1                20.5  Non-frequent customer
48        1                20.5  Non-frequent customer
49        1                20.5  Non-frequent customer
50        1                20.5  Non-frequent customer
51        1                20.5  Non-frequent customer
52        1                20.5  Non-frequent customer
53        1                20.5  Non-frequent customer
54        1                20.5  Non-frequent customer
55        1                20.5  Non-frequent customer
56        1                20.5  Non-frequent customer
57        1                20.5  Non-frequent customer
58        1                20.5  Non-frequent customer
59        2                13.0       Regular customer

# 06. Exporting Data

In [117]:
# export df_opm as orders_products_merged_filtered_flagged.pkl
df_opm.to_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_merged_filtered_flagged.pkl'))